import { createHash } from 'node:crypto'
import { writeFileSync } from 'node:fs'
import { pathToFileURL } from 'node:url'
import { renderToStaticMarkup } from 'react-dom/server'
import { TechIconSprite } from '../src/components/tech-icons.tsx'

/** public/tech-icons.svg: every tech brand mark as a <symbol>, served as
    one file that TechIcon's <use> points into. Its content hash is the
    URL's ?v=, so the file can be cached immutably (vite.config.ts) and
    still bust when it changes. Regenerate with `pnpm icons` after
    editing tech-icons.tsx (a test fails if stale). */
export function techIconSpriteFile(): string {
  return `${renderToStaticMarkup(<TechIconSprite />)}\n`
}

export function spriteVersion(file: string): string {
  return createHash('sha256').update(file).digest('hex').slice(0, 10)
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const file = techIconSpriteFile()
  writeFileSync('public/tech-icons.svg', file)
  writeFileSync(
    'src/components/tech-icon-sprite-version.ts',
    `// generated by \`pnpm icons\` — content hash of public/tech-icons.svg\nexport const TECH_ICON_SPRITE_VERSION = '${spriteVersion(file)}'\n`,
  )
}
